#!/usr/bin/env python3
"""Origin Style Studio

一个可视化小工具：
- 选择手绘风格预设（不止配色）
- 自定义透明度、边框、填充样式
- 生成可在 Origin Script Window 直接执行的 OGS 脚本
"""

from __future__ import annotations

import tkinter as tk
from pathlib import Path
from tkinter import filedialog, messagebox, ttk

PRESETS: dict[str, dict] = {
    "Marker 手绘马克笔": {
        "palette": ["#E67E80", "#F7BF69", "#8DC792", "#7BAEE4", "#B49EDB", "#71C4C9", "#F4A381", "#BCBCBC"],
        "transparency": 15,
        "line_width": 1.2,
        "fill_mode": 1,
    },
    "Watercolor 水彩": {
        "palette": ["#F2A7B5", "#F8D69D", "#B6DDB8", "#A8C8EA", "#CBB9E8", "#9ED9DC", "#F8C9B0", "#D7D7D7"],
        "transparency": 35,
        "line_width": 0.8,
        "fill_mode": 1,
    },
    "Sketch 铅笔草图": {
        "palette": ["#8A8A8A", "#A5A5A5", "#757575", "#9A9A9A", "#B0B0B0", "#6E6E6E", "#8F8F8F", "#C1C1C1"],
        "transparency": 5,
        "line_width": 1.8,
        "fill_mode": 9,
    },
    "Comic 漫画分镜": {
        "palette": ["#FF6B6B", "#FFD93D", "#6BCB77", "#4D96FF", "#B983FF", "#3DDAD7", "#FF8E3C", "#3A3A3A"],
        "transparency": 0,
        "line_width": 2.2,
        "fill_mode": 1,
    },
}


def hex_to_rgb(hex_color: str) -> tuple[int, int, int]:
    hex_color = hex_color.strip().lstrip("#")
    if len(hex_color) != 6:
        raise ValueError(f"Invalid hex color: {hex_color}")
    return tuple(int(hex_color[i : i + 2], 16) for i in (0, 2, 4))


def make_ogs(style_name: str, palette: list[str], transparency: int, line_width: float, fill_mode: int) -> str:
    lines: list[str] = [
        "// Auto generated by Origin Style Studio",
        f"// style: {style_name}",
        "[Main]",
        "int nColorStart = 1;",
        f"int nColorNum = {len(palette)};",
    ]

    for i, hx in enumerate(palette, start=1):
        r, g, b = hex_to_rgb(hx)
        lines.append(f"color({i}) = rgb({r}, {g}, {b});")

    lines += [
        "type \"[StyleStudio] applying...\";",
        "int nLayers = page.nlayers;",
        "int iLayer, iPlot;",
        "if(nLayers <= 0) { type \"[StyleStudio] No active graph page/layer.\"; break 1; }",
        "for(iLayer = 1; iLayer <= nLayers; iLayer++)",
        "{",
        "    layer -s %(iLayer);",
        "    int nPlots = layer.nplots;",
        "    if(nPlots <= 0) continue;",
        "    for(iPlot = 1; iPlot <= nPlots; iPlot++)",
        "    {",
        "        int idx = mod(iPlot-1, nColorNum) + nColorStart;",
        "        range rP = %(iLayer)!%(iPlot);",
        "        set rP -c %(idx);",
        "        set rP -k %(idx);",
        f"        set rP -kf {fill_mode};",
        f"        set rP -t {transparency};",
        f"        set rP -w {line_width};",
        "    }",
        "    legendupdate mode:=1;",
        "}",
        f"type \"[StyleStudio] 已应用风格: {style_name}\";",
    ]
    return "\n".join(lines) + "\n"


class App(tk.Tk):
    def __init__(self) -> None:
        super().__init__()
        self.title("Origin Style Studio")
        self.geometry("760x540")

        self.style_name = tk.StringVar(value=list(PRESETS.keys())[0])
        self.transparency = tk.IntVar(value=15)
        self.line_width = tk.DoubleVar(value=1.2)
        self.fill_mode = tk.IntVar(value=1)
        self.output_file = tk.StringVar(value=str(Path.cwd() / "origin" / "style_studio_custom.ogs"))

        self.palette_entries: list[tk.Entry] = []

        self._build_ui()
        self._load_preset()

    def _build_ui(self) -> None:
        frm = ttk.Frame(self, padding=12)
        frm.pack(fill="both", expand=True)

        ttk.Label(frm, text="风格预设").grid(row=0, column=0, sticky="w")
        cb = ttk.Combobox(frm, textvariable=self.style_name, values=list(PRESETS.keys()), state="readonly", width=30)
        cb.grid(row=0, column=1, sticky="w")
        cb.bind("<<ComboboxSelected>>", lambda _e: self._load_preset())

        ttk.Label(frm, text="透明度 (0-80)").grid(row=1, column=0, sticky="w")
        ttk.Scale(frm, from_=0, to=80, variable=self.transparency, orient="horizontal", length=280).grid(row=1, column=1, sticky="w")

        ttk.Label(frm, text="边框线宽 (0.5-4)").grid(row=2, column=0, sticky="w")
        ttk.Scale(frm, from_=0.5, to=4.0, variable=self.line_width, orient="horizontal", length=280).grid(row=2, column=1, sticky="w")

        ttk.Label(frm, text="填充模式 (1=实心,9=纹理)").grid(row=3, column=0, sticky="w")
        ttk.Spinbox(frm, from_=1, to=20, textvariable=self.fill_mode, width=8).grid(row=3, column=1, sticky="w")

        ttk.Separator(frm, orient="horizontal").grid(row=4, column=0, columnspan=4, sticky="ew", pady=10)
        ttk.Label(frm, text="调色板 HEX（8个）").grid(row=5, column=0, sticky="w")

        pfrm = ttk.Frame(frm)
        pfrm.grid(row=6, column=0, columnspan=4, sticky="w")
        for i in range(8):
            ttk.Label(pfrm, text=f"C{i+1}").grid(row=i // 4, column=(i % 4) * 2, sticky="e", padx=(0, 4), pady=4)
            e = ttk.Entry(pfrm, width=12)
            e.grid(row=i // 4, column=(i % 4) * 2 + 1, sticky="w", padx=(0, 12), pady=4)
            self.palette_entries.append(e)

        ttk.Separator(frm, orient="horizontal").grid(row=7, column=0, columnspan=4, sticky="ew", pady=10)

        ttk.Label(frm, text="输出 OGS 文件").grid(row=8, column=0, sticky="w")
        ttk.Entry(frm, textvariable=self.output_file, width=60).grid(row=8, column=1, sticky="w")
        ttk.Button(frm, text="选择...", command=self._pick_output).grid(row=8, column=2, sticky="w")

        ttk.Button(frm, text="生成 OGS", command=self._export_ogs).grid(row=9, column=1, sticky="w", pady=12)
        ttk.Button(frm, text="复制 Origin 执行命令", command=self._copy_run_command).grid(row=9, column=2, sticky="w", pady=12)

        tips = (
            "在 Origin Script Window 执行:\n"
            "run.section(\"D:\\\\path\\\\to\\\\style_studio_custom.ogs\", Main);"
        )
        ttk.Label(frm, text=tips, foreground="#444").grid(row=10, column=0, columnspan=4, sticky="w")

    def _load_preset(self) -> None:
        p = PRESETS[self.style_name.get()]
        self.transparency.set(p["transparency"])
        self.line_width.set(p["line_width"])
        self.fill_mode.set(p["fill_mode"])
        for i, hx in enumerate(p["palette"]):
            self.palette_entries[i].delete(0, tk.END)
            self.palette_entries[i].insert(0, hx)

    def _pick_output(self) -> None:
        path = filedialog.asksaveasfilename(
            title="选择输出 OGS 文件",
            defaultextension=".ogs",
            filetypes=[("OGS file", "*.ogs"), ("All files", "*.*")],
            initialfile="style_studio_custom.ogs",
        )
        if path:
            self.output_file.set(path)

    def _collect_palette(self) -> list[str]:
        vals = [e.get().strip() for e in self.palette_entries]
        for v in vals:
            hex_to_rgb(v)
        return vals

    def _export_ogs(self) -> None:
        try:
            palette = self._collect_palette()
            text = make_ogs(
                self.style_name.get(),
                palette,
                int(self.transparency.get()),
                float(self.line_width.get()),
                int(self.fill_mode.get()),
            )
            out = Path(self.output_file.get())
            out.parent.mkdir(parents=True, exist_ok=True)
            out.write_text(text, encoding="utf-8")
            messagebox.showinfo("成功", f"已生成: {out}")
        except Exception as exc:  # noqa: BLE001
            messagebox.showerror("错误", str(exc))

    def _copy_run_command(self) -> None:
        out = str(Path(self.output_file.get()).resolve()).replace("\\", "\\\\")
        cmd = f'run.section("{out}", Main);'
        self.clipboard_clear()
        self.clipboard_append(cmd)
        messagebox.showinfo("已复制", f"已复制到剪贴板:\n{cmd}")


if __name__ == "__main__":
    App().mainloop()
